INSERT INTO LOS_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL)
VALUES (1, 'Leandro', 'leco', '1234','leandro@gmail.com');
INSERT INTO LOS_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL)
VALUES (2, 'Stephani', 'ste', '1234','stephani@gmail.com');
INSERT INTO LOS_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL)
VALUES (3, 'Leonardo', 'leo', '1234','leonardo@gmail.com');

ALTER SEQUENCE LOS_USUARIO_ID_SEQ RESTART WITH 4;

INSERT INTO LOS_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO LOS_PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO LOS_PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE LOS_PERFIL_SEQ RESTART WITH 4;

INSERT INTO LOS_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO LOS_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO LOS_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE LOS_RECURSO_SEQ RESTART WITH 4;