INSERT INTO LOS_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL)
VALUES (1, 'Leandro', 'leco', '1234','leandro@gmail.com');

ALTER SEQUENCE LOS_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO LOS_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO LOS_PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO LOS_PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE LOS_PERFIL_SEQ RESTART WITH 2;
